import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Appbar } from "./components/Appbar";
import { cn } from '@/lib/utils';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontHeading = Inter({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-heading',
  })
  
  const fontBody = Inter({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-body',
  })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`flex-container flex-col antialiased ${fontHeading.variable} ${fontBody.variable}`}>
        <Appbar/>
        {children}
      </body>
    </html>
  );
}
